1) Create a Numpy array of size 4 x 5.

In [ ]:
import numpy as np
matrix2=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(matrix)

[[1 2]
 [3 4]]


2) Randomly initialize the array.

In [ ]:

rand=np.random.rand(5)
print(rand)


[0.73185652 0.68576186 0.76943774 0.46184904 0.11958791]


3) Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.

In [ ]:

matrix=np.array([[1,2],[3,4]])
print(matrix.transpose())

[[1 3]
 [2 4]]


4) Create another matrix of size 5 x 4 and randomly initialize it.

In [ ]:

rand=np.random.rand(5,4)
print(rand)

[[0.60204985 0.6934171  0.4965878  0.31822933]
 [0.76928633 0.04510927 0.00197494 0.85438988]
 [0.83763623 0.28833274 0.24369996 0.48256469]
 [0.06606928 0.72912193 0.16714786 0.91013794]
 [0.86440901 0.64262462 0.26725636 0.82583221]]


5) Perform Matrix multiplication.
6) Perform element wise matrix multiplication.

In [ ]:
matrix1=np.array([[3,4],[5,4]])*matrix
print(matrix1)
matrix1=np.dot(np.array([[3,4],[5,4]]),matrix)
print(matrix1)
matrix1=matrix1.T
print(matrix1)

[[ 3  8]
 [15 16]]
[[15 22]
 [17 26]]
[[15 17]
 [22 26]]


7) Find mean, median of the numpy array created.





In [ ]:
print(np.mean(matrix1))
print(np.mean(matrix1,axis=0))
print(np.mean(matrix1,axis=1))
print(np.median(matrix1))

20.0
[18.5 21.5]
[16. 24.]
19.5


8) Obtain each row in the second column of the first array.

In [ ]:
print(matrix2[:,1])

[2 2 2 2 2]


9) Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [ ]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
data=pd.read_csv('/content/drive/MyDrive/Iris.csv - Iris.csv.csv')
centered=data['SepalLengthCm']-np.mean(data['SepalLengthCm'],axis=0)
print(centered)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
0     -0.743333
1     -0.943333
2     -1.143333
3     -1.243333
4     -0.843333
         ...   
145    0.856667
146    0.456667
147    0.656667
148    0.356667
149    0.056667
Name: SepalLengthCm, Length: 150, dtype: float64
